complaints/urls.py
from django.urls import path
from .import views

app_name = 'complaints'

urlpatterns = [
    path('new/', views.CreateComplaint, name="create"),
    path('list/<slug:type>/<int:const>/<int:select_all>', views.ComplaintList.as_view(), name="complaint_list"),
    
    path('display_all/', views.allConstStatus, name='display_all'),
    path('get_const_num/', views.get_const_num, name='get_const_num'),
    path('update_view_status/<int:pk>/', views.update_view, name='update_view'),
    path('get_type_num/', views.get_type_num, name='get_type_num'),
    path('get_type/', views.get_type, name='get_type'),
    path('display_const_stats/<int:const>/', views.display_const_stats, name='display_const_stats'),
    path('display_type_stats/<slug:type>/', views.display_type_stats, name='display_type_stats'),
    path('details/<int:pk>/', views.ComplaintDetail.as_view(), name='single'),
    path('by/<slug:username>/', views.UserComplaints.as_view(), name='user_complaints'),
    path('post/<int:pk>/', views.add_comment_to_complaint, name='add_comment_to_complaint'),
    path('like/<int:pk>/', views.likes, name='like'),
    path('dislike/<int:pk>/', views.dislikes, name='dislike'),
]

filecomplaint/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views
from django.conf import settings
# from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static


from .import views


admin.site.site_header = 'ELECTION COMMISSION OF INDIA'
admin.site.site_title = 'Election Commission Of India Administration'
admin.site.index_title = 'Election Commission Of India Administration'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePage.as_view(), name='home'),
    path('fault/<str:fault>/', views.fault_page, name='fault'),
    path('accounts/', include('accounts.urls',namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('welcome/', views.WelcomePage.as_view(),name='welcome'),
    path('thanks/', views.ThanksPage.as_view(),name='thanks'),
    path('complaints/', include('complaints.urls',namespace='complaints')),
    path('sms/', include('sms.urls',namespace='sms')),
    path('admin/password_reset/', auth_views.PasswordResetView.as_view(), name='admin_password_reset'),
    path('admin/password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sms/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.urls import path
from .import views

app_name = 'sms'


urlpatterns = [
    path('send/<str:complaint_type>/<int:msg_type>/<slug:name>/<int:phone_num>/<int:pk>/', views.send, name='send'),
    path('send_otp/<int:pk>/', views.send_otp, name='send_otp'),
    

]

complaints/models.py
from django.urls import reverse
from django.db import models
from accounts import models as acc_models
from django.contrib.auth import get_user_model
User = get_user_model()

# Create your models here.


class Complaint(models.Model):

    user = models.ForeignKey(
        User, related_name='complaints', on_delete=models.CASCADE)
    

    COMPLAINT_CHOICES = []
    type_list = [u['type'] for u in acc_models.ComplaintType.objects.all().values('type')]
    for temp in type_list:
        COMPLAINT_CHOICES.append((temp,temp))

    choice = models.CharField(
        max_length=50, choices=COMPLAINT_CHOICES, blank=False)
    description = models.TextField(blank=True)
    file_upload = models.FileField(
        upload_to='files', blank=True)
    file_upload1 = models.FileField(
        upload_to='files', blank=True)
    file_upload2 = models.FileField(
        upload_to='files', blank=True)
    file_upload3 = models.FileField(
        upload_to='files', blank=True)
    file_upload4 = models.FileField(
        upload_to='files', blank=True)
    file_upload5 = models.FileField(
        upload_to='files', blank=True)

    created_at = models.DateTimeField(auto_now=True)

    viewed_complaint = models.BooleanField(default=False)

    is_liked = models.BooleanField(default=False)
    is_disliked = models.BooleanField(default=False)

    def __str__(self):
        return self.choice

    def get_absolute_url(self):
        return reverse('home')

    def Constituency_number(self):
        return self.user.voter_details.cons_no
    
    def Booth_number(self):
        return self.user.voter_details.booth_no

    class Meta():
        ordering = ['created_at']
        unique_together = ["user", "choice"]


        
        #model Comment
class Comment(models.Model):
    complaint = models.ForeignKey(
        'complaints.Complaint', related_name='comments', on_delete=models.CASCADE)
    text = models.TextField()
    created_date = models.DateTimeField(auto_now=True)

    def get_absolute_url(self):
        return reverse('complaints:single', kwargs={'pk': self.pk})

    def __str__(self):
        return self.text

complaints/forms.py
from django import forms
from .import models
from accounts import models as acc_models


class ComplaintForm(forms.ModelForm):

    class Meta():
        model = models.Complaint
        exclude = ['user', 'created_at', 'viewed_complaint', 'is_liked', 'is_disliked']


class get_number(forms.Form):

    const = forms.IntegerField()


class get_type_form(forms.Form):

    COMPLAINT_CHOICES = [('All','All')]
    type_list = [u['type']
                 for u in acc_models.ComplaintType.objects.all().values('type')]
    for temp in type_list:
        COMPLAINT_CHOICES.append((temp, temp))

    type = forms.ChoiceField(choices=COMPLAINT_CHOICES)


class get_type_num_form(forms.Form):

    const = forms.IntegerField(initial=0)

    select_all = forms.BooleanField(required=False)

    COMPLAINT_CHOICES = [('All', 'All')]
    type_list = [u['type']
                 for u in acc_models.ComplaintType.objects.all().values('type')]
    for temp in type_list:
        COMPLAINT_CHOICES.append((temp, temp))

    type = forms.ChoiceField(choices=COMPLAINT_CHOICES)


class CommentForm(forms.ModelForm):

    class Meta():
        model = models.Comment
        fields = ('text',)

complaints/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import generic
from django.urls import reverse_lazy
from .import models
from .import forms
from accounts import models as acc_models
from django.utils.text import slugify
from django.contrib.auth import get_user_model
from django.http import Http404, HttpResponse
from django.contrib.auth.decorators import login_required
import json
User = get_user_model()

def CheckBadWords(list2):
    list3=[]
    for item2 in list2:
        list3.append(f'{item2}\n'.lower())

    list1=open("C:/Users/Aditya/Desktop/WebDev/Django/ECI_Website/ECI_Website/complaints/bad_words.txt",'r').readlines()
    for item1 in list3:
        for item2 in list1:
            if(item1==item2):
                return False
    return True



@login_required
def CreateComplaint(request):
    if request.method == 'POST':
        form = forms.ComplaintForm(request.POST, request.FILES)
        if form.is_valid():
            try:
                list2=str(form.cleaned_data['description']).split()
                res=CheckBadWords(list2)
                if not res:
                    return redirect('fault', fault=f'YOU CANNOT USE THESE OFFENSIVE WORD IN THE DESCRIPTION')
                complaint = form.save(commit=False)
                complaint.user = request.user
                complaint.save()
                pk=0
                return redirect('sms:send', complaint_type=slugify(complaint.choice), msg_type=2, name=complaint.user.username, phone_num = complaint.user.voter_details.phone_num, pk=pk)
            except:
                return redirect('fault', fault ="The record for this complaint already exists and is under progress")

        else:
            return redirect('fault', fault ="Something went wrong try again")
    else:
        form = forms.ComplaintForm()
    return render(request, 'complaint/complaint_form.html', {'form': form})

# All Data Display for the country


def allConstStatus(request):
    type_dict = acc_models.ComplaintType.objects.all().values('type')
    type_list = [u['type'] for u in type_dict]
    type_count = []

    dict = {}
    for type in type_list:
        num = models.Complaint.objects.all().filter(choice__iexact=type).count()
        dict[type] = num
        type_count.append(num)

    # Data for charts
    data = {
        "label": type_list,
        "value": type_count

    }
    jsondata = json.dumps(data)
    return render(request, 'complaint/display_all_stats.html', {'jsondata': jsondata, 'dict': dict})


# Get The Constitunecy number to display stats


def get_const_num(request):
    if request.method == 'POST':
        form = forms.get_number(request.POST)
        if form.is_valid():
            const = form.cleaned_data['const']
            const_list = [u['id']
                          for u in acc_models.Constituency.objects.all().values('id')]

            if not const in const_list:
                data = {
                    'const': [const],
                }
                jsondata = json.dumps(data)
                form = forms.get_number()
                return render(request, 'complaint/get_constituency.html', {'form': form, 'jsondata': jsondata})

            return redirect('complaints:display_const_stats', const=const)
        # const = request.POST['const']
    else:
        form = forms.get_number()
    return render(request, 'complaint/get_constituency.html', {'form': form})


# Get The type of complaint to display stats


def get_type(request):
    if request.method == 'POST':
        form = forms.get_type_form(request.POST)
        if form.is_valid():
            type = form.cleaned_data['type']
            type = slugify(type)
            return redirect('complaints:display_type_stats', type=type)
        # const = request.POST['const']
    else:
        form = forms.get_type_form()
    return render(request, 'complaint/get_complaint_type.html', {'form': form})


def get_type_num(request):
    if request.method == 'POST':
        form = forms.get_type_num_form(request.POST)
        if form.is_valid():
            type = form.cleaned_data['type']
            type = slugify(type)
            const = form.cleaned_data['const']
            select_all = form.cleaned_data['select_all']
            select_all = int(select_all)
            const_list = [u['id']
                          for u in acc_models.Constituency.objects.all().values('id')]
            if not const in const_list and not select_all:
                data = {
                    'const': [const],
                }
                jsondata = json.dumps(data)
                form = forms.get_type_num_form()
                return render(request, 'complaint/get_complaint_type_num.html', {'form': form, 'jsondata': jsondata})
            return redirect('complaints:complaint_list', type=type, const=const, select_all=select_all)
        # const = request.POST['const']
    else:
        form = forms.get_type_num_form()
    return render(request, 'complaint/get_complaint_type_num.html', {'form': form})


# Display stats of a particular constituency


def display_const_stats(request, const):
    type_dict = acc_models.ComplaintType.objects.all().values('type')
    type_list = [u['type'] for u in type_dict]
    type_count = []

    dict = {}
    for type in type_list:
        num = models.Complaint.objects.all().filter(
            choice__iexact=type, user__voter_details__cons_no__iexact=const).count()
        dict[type] = num
        type_count.append(num)
    data = {
        "label": type_list,
        "value": type_count

    }

    jsondata = json.dumps(data)
    return render(request, 'complaint/display_const_stats.html', {'jsondata': jsondata, 'dict': dict, 'const': const})


#  Display stats of a particular type


def display_type_stats(request, type):
    dict = {}
    const_list = []
    num_list = []
    id_list = [u['id'] for u in acc_models.Constituency.objects.all().values('id')]
    type = type.replace("-", " ")
    if type!='all':
        for id in id_list:
            num = models.Complaint.objects.all().filter(
                choice__iexact=type, user__voter_details__cons_no__iexact=id).count()
            dict.update({id: num})
            const_list.append(str(id))
            num_list.append(num)
    else:
        for id in id_list:
            num = models.Complaint.objects.all().filter(user__voter_details__cons_no__iexact=id).count()
            dict.update({id: num})
            const_list.append(str(id))
            num_list.append(num)
    data = {
        "label": const_list,
        "value": num_list

    }
    jsondata = json.dumps(data)
    return render(request, 'complaint/display_type_stats.html', {'dict': dict, 'jsondata': jsondata, 'type': type})

# Updating viewed boolean value


@login_required
def update_view(request, pk):
    present_complaint = models.Complaint.objects.get(pk=pk)
    if present_complaint.viewed_complaint == False:
        present_complaint.viewed_complaint = True
        present_complaint.save()
        return redirect('sms:send',complaint_type=(present_complaint.choice), msg_type=3, name=present_complaint.user.username, phone_num=present_complaint.user.voter_details.phone_num, pk=pk)
    else:
        return redirect('complaints:single', pk=pk)

# Display stats for govt


class ComplaintList(generic.ListView, LoginRequiredMixin):
    model = models.Complaint
    template_name = 'complaint/complaint_list.html'

    def get_queryset(self):
        
        queryset = super().get_queryset()
        type_new = self.kwargs.get("type").replace("-", " ")
        select_all = self.kwargs.get("select_all")
        
        if type_new == 'all' and select_all == 0:
            return queryset.filter(user__voter_details__cons_no__iexact=self.kwargs.get("const"))

        if type_new == 'all' and select_all == 1:
            return queryset

        if type_new != 'all' and select_all == 1:
            return queryset.filter(choice__iexact=type_new)

        return queryset.filter(choice__iexact=type_new, user__voter_details__cons_no__iexact=self.kwargs.get("const"))

# Display stat for particular complaint


class ComplaintDetail(generic.DetailView, LoginRequiredMixin):
    model = models.Complaint
    template_name = 'complaint/complaint_detail.html'


class UserComplaints(LoginRequiredMixin, generic.ListView):
    model = models.Complaint
    template_name = "complaint/user_complaint_list.html"

    def get_queryset(self):
        try:
            self.complaint_user = User.objects.prefetch_related(
                "complaints").get(username__iexact=self.kwargs.get("username"))
        except User.DoesNotExist:
            raise Http404
        else:
            return self.complaint_user.complaints.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["complaint_user"] = self.complaint_user
        return context


@login_required
def add_comment_to_complaint(request, pk):
    complaint = get_object_or_404(models.Complaint, pk=pk)

    if request.method == 'POST':
        form = forms.CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.complaint = complaint
            comment.save()
            return redirect('sms:send',complaint_type=slugify(complaint.choice), msg_type=4, name=complaint.user.username, phone_num=complaint.user.voter_details.phone_num, pk=complaint.pk)

    else:
        form = forms.CommentForm()
    return render(request, 'complaint/comment_form.html', {'form': form})





@login_required
def likes(request,pk):
    complaint = models.Complaint.objects.get(pk__iexact = pk)
    if complaint.is_liked == True:
        complaint.is_liked = False
        complaint.save()
    elif complaint.is_liked == False:
        complaint.is_liked = True
        complaint.is_disliked = False

complaints/templates/complaint/chart.html
<canvas id="myChart" width="200" height="200"></canvas>
<script>
    var ctx = document.getElementById("myChart").getContext('2d');
    var myChart = new Chart(ctx, {
        type: 'bar',
        data: {
            labels: jsonobject.label,
            datasets: [{
                label: '# of Complaints',
                data: jsonobject.value,
                backgroundColor: [
                    'rgba(255, 99, 132, 0.2)',
                    'rgba(54, 162, 235, 0.2)',
                    'rgba(255, 206, 86, 0.2)',
                    'rgba(75, 192, 192, 0.2)',
                    'rgba(153, 102, 255, 0.2)',
                    'rgba(255, 159, 64, 0.2)'
                ],
                borderColor: [
                    'rgba(255,99,132,1)',
                    'rgba(54, 162, 235, 1)',
                    'rgba(255, 206, 86, 1)',
                    'rgba(75, 192, 192, 1)',
                    'rgba(153, 102, 255, 1)',
                    'rgba(255, 159, 64, 1)'
                ],
                borderWidth: 1
            }]
        },
        options: {
            scales: {
                yAxes: [{
                    ticks: {
                        beginAtZero: true
                    }
                }]
            }
        }
    });
</script>

complaints/templates/complaint/comment_form.html
{% extends "complaint/complaint_base.html" %}

{% block complaint_content %}
  <h1>New Comment</h1>
  <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Post</button>
  </form>
{% endblock %}

complaints/templates/complaint/complaint_base.html
{% extends "base.html" %}

{% block content %}
    {% block pre_complaint %}{% endblock %}
    {% block complaint_content %}{% endblock %}
    {% block post_complaint %}{% endblock %}
{% endblock %}

complaints/templates/complaint/complaint_detail.html
{% extends "complaint/complaint_base.html" %}

{% block complaint_content %}
<h1>{{ complaint.choice }}</h1>
<h1>{{ complaint.user.voter_details.cons_no }}</h1>
<h1>{{ complaint.user.voter_details.booth_no }}</h1>

{% if complaint.viewed_complaint == 1 %}
<h2>Status: Seen</h2>
{% else %}
<h2>Status: Unseen</h2>
{% endif %}

{% if user.is_authenticated and user.username in govname_list %}
<h1>{{ complaint.user.username }}</h1>
{% endif %}
<p>{{ complaint.created_at }}</p>
<p>{{ complaint.description }}</p>
{% if complaint.file_upload %}
<a href="{{ complaint.file_upload.url }}" target="_blank">View File</a>
{% endif %}
{% if complaint.file_upload1 %}
<a href="{{ complaint.file_upload1.url }}" target="_blank">View File</a>
{% endif %}
{% if complaint.file_upload2 %}
<a href="{{ complaint.file_upload2.url }}" target="_blank">View File</a>
{% endif %}
{% if complaint.file_upload3 %}
<a href="{{ complaint.file_upload3.url }}" target="_blank">View File</a>
{% endif %}
{% if complaint.file_upload4 %}
<a href="{{ complaint.file_upload4.url }}" target="_blank">View File</a>
{% endif %}
{% if complaint.file_upload5 %}
<a href="{{ complaint.file_upload5.url }}" target="_blank">View File</a>
{% endif %}

{% if user.is_authenticated and not user.username in govname_list %}
<p>Like: <a href="{% url 'complaints:like' pk=complaint.pk %}">{{complaint.is_liked}}</a></p>
<p>Dislike: <a href="{% url 'complaints:dislike' pk=complaint.pk %}">{{complaint.is_disliked}}</a></p>
{% endif %}

{% if user.is_authenticated and user.username in govname_list %}
<p>Like: {{complaint.is_liked}}</p>
<p>Dislike: {{complaint.is_disliked}}</p>
{% endif %}

<h2>Comments</h2>

{% if user.is_authenticated and user.username in govname_list %}

<p><a href="{% url 'complaints:add_comment_to_complaint' pk=complaint.pk %}">Add Comment</a></p>

{% endif %}

{% for comment in complaint.comments.all %}
    <ul>
        <li>
            <p>{{ comment.text|safe|linebreaks }}</p>
            
        </li>
    </ul>
    {% empty %}
    <p>
        NO COMMENTS POSTED!!!
    </p>
{% endfor %}
{% endblock %}

complaints/templates/complaint/complaint_form.html
{% extends "complaint/complaint_base.html" %}

{% block complaint_content %}

<form enctype="multipart/form-data" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="File">
</form>

{% endblock %}

complaints/templates/complaint/complaint_list.html
{% extends "complaint/complaint_base.html" %}

{% block complaint_content %}
    <ul>
        {% for com in complaint_list %}
        <li>
            {{com.choice}} 
            {{com.user.voter_details.cons_no}} 
            {{com.user.voter_details.booth_no}}
            {% if com.viewed_complaint == 0 %}
            <h3>Unseen</h3>
            {% endif %}
            <a href="{% url 'complaints:update_view' pk=com.pk %}">View Details</a>
        </li>
        {% endfor %}
    </ul>
{% endblock %}

complaints/templates/complaint/display_all_stats.html
{% extends "base.html" %}


{% block content %}

<h1> Stats</h1>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.3/Chart.js"></script>
<script>
var jsonobject = JSON.parse('{{ jsondata | escapejs }}');
</script>
{% include "complaint/chart.html" %}

<ul>
    {% for key,value in dict.items %}
    <li>
        <p>
            {{key}}:{{value}}
        </p>
    </li>
    {% endfor %}
</ul>




{% endblock %}

complaints/templates/complaint/display_const_stats.html
{% extends "complaint/complaint_base.html" %}

{% block content %}
<h1> Stats for {{const}}</h1>

<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.3/Chart.js"></script>
<script>
var jsonobject = JSON.parse('{{ jsondata | escapejs }}');

</script>
{% include "complaint/chart.html" %}


<ul>
    {% for key,value in dict.items %}
        <li>
            <p>
                {{key}}:{{value}}
            </p>
        </li>
        
        {% endfor %}
</ul>

{% endblock %}

complaints/templates/complaint/display_type_stats.html
{% extends "complaint/complaint_base.html" %}

{% block content %}

<h1> Stats for {{type}}</h1>


<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.3/Chart.js"></script>
<script>
var jsonobject = JSON.parse('{{ jsondata | escapejs }}');
</script>
<canvas id="myChart" width="200" height="200"></canvas>
<script>
    var ctx = document.getElementById("myChart").getContext('2d');
    var myChart = new Chart(ctx, {
        type: 'horizontalBar',
        data: {
            labels: jsonobject.label,
            datasets: [{
                label: '',
                data: jsonobject.value,
                backgroundColor: [
                    'rgba(255, 99, 132, 0.2)',
                    'rgba(54, 162, 235, 0.2)',
                    'rgba(255, 206, 86, 0.2)',
                    'rgba(75, 192, 192, 0.2)',
                    'rgba(153, 102, 255, 0.2)',
                    'rgba(255, 159, 64, 0.2)'
                ],
                borderColor: [
                    'rgba(255,99,132,1)',
                    'rgba(54, 162, 235, 1)',
                    'rgba(255, 206, 86, 1)',
                    'rgba(75, 192, 192, 1)',
                    'rgba(153, 102, 255, 1)',
                    'rgba(255, 159, 64, 1)'
                ],
                borderWidth: 1
            }]
        },
        options: {
            scales: {
                yAxes: [{
                    ticks: {
                        beginAtZero: true
                    }
                }]
            }
        }
    });
</script>

<ul>
    {% for key,value in dict.items %}
    <li>
        <p>{{key}}:{{value}}</p>
    </li>
    {% endfor %}
</ul>


{% endblock %}

complaints/templates/complaint/get_complaint_type.html
{% extends "complaint/complaint_base.html" %}

{% block content %}

    
    <form action="{% url 'complaints:get_type' %}" method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="View">
    </form>

    <!-- <select name="type">
        <option value="Booth Capturing">Booth Capturing</option>
        <option value="Bogus Voting">Bogus Voting</option>
        <option value="Obstruction to Voters">Obstruction to Voters</option>
        <option value="Money Distribution">Money Distribution</option>
        <option value="Liquor Distribution">Liquor Distribution</option>
        <option value="No Armed Forces">No Armed Forces</option>
        <option value="EVM Malfunction">EVM Malfunction</option>
    </select> -->

{% endblock %}

complaints/templates/complaint/get_complaint_type_num.html
{% extends "complaint/complaint_base.html" %}

{% block content %}

{% if jsondata %}

<script>
var jsonobject = JSON.parse('{{ jsondata | escapejs }}');

var cc = jsonobject['const'];

window.alert(`${cc} is not a valid constituency number.`);



</script>
{% endif %}

    
    <form action="{% url 'complaints:get_type_num' %}" method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="View">
    </form>



{% endblock %}

complaints/templates/complaint/get_constituency.html
{% extends "complaint/complaint_base.html" %}

{% block content %}
{% if jsondata %}

<script>
var jsonobject = JSON.parse('{{ jsondata | escapejs }}');

var cc = jsonobject['const'];

window.alert(`${cc} is not a valid constituency number.`);



</script>
{% endif %}
    
    <form action="{% url 'complaints:get_const_num' %}" method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="View">
    </form>
    
{% endblock %}

complaints/templates/complaint/user_complaint_list.html
{% extends "complaint/complaint_base.html" %}

{% block complaint_content %}
    <ul>
        {% for com in complaint_list %}
        <li>
            {{com.choice}} 
            {{com.user.voter_details.cons_no}} 
            {{com.user.voter_details.booth_no}}
            <a href="{% url 'complaints:single' pk=com.pk %}">View Details</a>
        </li>
        {% endfor %}
    </ul>
{% endblock %}