accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.urls import path
from .import views

app_name = 'accounts'

urlpatterns = [
    # path('login/',auth_views.LoginView.as_view(template_name = 'accounts/login.html'), name = 'login'),
    path('login/', views.TempLogin, name='login'),
    path('login/1/<int:pk>/', views.login, name='permanent_login'),
    path('logout/',auth_views.LogoutView.as_view(), name = 'logout'),
    path('add_user/',views.add_user,name='add_user'),
    path('add_voter/<str:username>/',views.add_voter,name='add_voter'),
    path('add_gov_user/',views.add_gov_user,name='add_gov_user'),
    path('add_gov_user_phone/<str:username>/',views.add_gov_user_phone,name='add_gov_user_phone'),
    path('add_constituency/',views.add_constituency, name = 'add_constituency'),
    path('add_complaint_type/',views.add_complaint_type, name = 'add_complaint_type'),
    path('update_constituency/',views.update_constituency, name = 'update_constituency'),
    path('constituency_list/', views.ConstituencyList.as_view(), name = 'constituency_list'),
]

complaints/urls.py
from django.urls import path
from .import views

app_name = 'complaints'

urlpatterns = [
    path('new/', views.CreateComplaint, name="create"),
    path('list/<slug:type>/<int:const>/<int:select_all>', views.ComplaintList.as_view(), name="complaint_list"),
    
    path('display_all/', views.allConstStatus, name='display_all'),
    path('get_const_num/', views.get_const_num, name='get_const_num'),
    path('update_view_status/<int:pk>/', views.update_view, name='update_view'),
    path('get_type_num/', views.get_type_num, name='get_type_num'),
    path('get_type/', views.get_type, name='get_type'),
    path('display_const_stats/<int:const>/', views.display_const_stats, name='display_const_stats'),
    path('display_type_stats/<slug:type>/', views.display_type_stats, name='display_type_stats'),
    path('details/<int:pk>/', views.ComplaintDetail.as_view(), name='single'),
    path('by/<slug:username>/', views.UserComplaints.as_view(), name='user_complaints'),
    path('post/<int:pk>/', views.add_comment_to_complaint, name='add_comment_to_complaint'),
    path('like/<int:pk>/', views.likes, name='like'),
    path('dislike/<int:pk>/', views.dislikes, name='dislike'),
]

filecomplaint/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views
from django.conf import settings
# from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static


from .import views


admin.site.site_header = 'ELECTION COMMISSION OF INDIA'
admin.site.site_title = 'Election Commission Of India Administration'
admin.site.index_title = 'Election Commission Of India Administration'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePage.as_view(), name='home'),
    path('fault/<str:fault>/', views.fault_page, name='fault'),
    path('accounts/', include('accounts.urls',namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('welcome/', views.WelcomePage.as_view(),name='welcome'),
    path('thanks/', views.ThanksPage.as_view(),name='thanks'),
    path('complaints/', include('complaints.urls',namespace='complaints')),
    path('sms/', include('sms.urls',namespace='sms')),
    path('admin/password_reset/', auth_views.PasswordResetView.as_view(), name='admin_password_reset'),
    path('admin/password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sms/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.urls import path
from .import views

app_name = 'sms'


urlpatterns = [
    path('send/<str:complaint_type>/<int:msg_type>/<slug:name>/<int:phone_num>/<int:pk>/', views.send, name='send'),
    path('send_otp/<int:pk>/', views.send_otp, name='send_otp'),
    

]

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title></title>

</head>
<body>
    
    <a href="{%  url 'home' %}">Home</a>
    <a href="{% url 'complaints:display_all' %}">Display</a>
    <a href="{% url 'complaints:get_const_num' %}">View Const Specific</a>
    <a href="{% url 'complaints:get_type' %}">View Type Specific</a>
    <a href="{% url 'accounts:constituency_list' %}">View Constituency List</a>
    {% if user.is_authenticated and user.username in govname_list %}
    <a href="{% url 'complaints:get_type_num' %}">View Special List</a>
    <a href="{% url 'accounts:add_user' %}">Add User</a>
    {% if user.gov.is_supergov %}
    <a href="{% url 'accounts:add_gov_user' %}">Add Gov user</a>
    <a href="{% url 'accounts:add_constituency' %}">Add Constituency</a>
    <a href="{% url 'accounts:add_complaint_type' %}">Add Complaint Type</a>
    <a href="{% url 'accounts:update_constituency' %}">Update Constituency</a>

    {% endif %}
    

    {% endif %}
    {% if user.is_authenticated %}
    {% block government %}
    {% if not user.username in govname_list %}
    <a href="{% url 'complaints:create' %}">Create New Complaint</a>
    <a href="{% url 'complaints:user_complaints' username=user.username %}">My complaints</a>
    {% endif %}
    {% endblock %}
        <a href="{% url 'accounts:logout' %}">Logout</a>
    {% else %}
        <a href="{% url 'accounts:login' %}">Login</a>
        
    {% endif %}
    {% block jquery %}
    {% endblock %}
    {% block content %}
    {% endblock %}
    <script
  src="https://code.jquery.com/jquery-3.3.1.min.js"
  integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
  crossorigin="anonymous"></script>
  <!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.3/Chart.js"></script> -->

</body>
</html>

templates/fault.html
{% extends 'base.html' %}

{% block content %}
	<p>{{fault}}</p>
{% endblock %}

templates/index.html
{% extends 'base.html' %}

{% block content %}
    <h1>Welcome</h1>

    <p>Likes: {{likes}}</p>
    <p>Dislikes: {{dislikes}}</p>
    <p>Complaints registered: {{max_complaints}}</p>
   	{% for id in max_id %}
   	<p>Constituency ID: {{id}}</p>
   	{% endfor %}

{% endblock %}

templates/thanks.html
{% extends 'base.html' %}

{% block content %}
    <h1>Thank You For Visiting!!!!!</h1>

{% endblock %}

templates/welcome.html
{% extends 'base.html' %}

{% block content %}
    <h1>You are now logged in..</h1>

{% endblock %}